---
- name: launch an instance
  os_server:
    state: present
    cloud: citycloud
    name: vm3
    image: 2feddaee-7c0d-4de1-a9c6-4a1c6be49cad
    key_name: jenkins3
    timeout: 200
    flavor: 2C-2GB-20GB
    security_groups: test-security,default
    userdata: |
      #cloud_config:
        package_update: true
        package_upgrade: true
        package_reboot_if_required: true
        hostname: 'gitServer'
        write_files:
          -content: |
              # My new /etc/hosts file
              127.0.0.1 localhost
              127.0.1.1 gitServer
              # The following lines are desirable for IPv6 capable hosts
              ::1 ip6-localhost ip6-loopback
              fe00::0 ip6-localnet
              ff00::0 ip6-mcastprefix
              ff02::1 ip6-allnodes
              ff02::2 ip6-allrouters
              ff02::3 ip6-allhosts
          path: /etc/hosts
        packages: apt-transport-https,ca-certificates,curl,software-properties-common,linux-image-extra-virtual,certbot
        fs_setup:
            ## rkt
          - device: /dev/vdb
            partition: 'auto'
            label: rkt
            filesystem: ext4
        mounts:
            - [ "LABEL=rkt", /mnt/docker_data ]
        runcmd:
          - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          - apt-get update
          - apt-get install -y docker-ce
        users:
          - default
          - name: jenkins
            plain_text_passwd: 'Test1234'
            sudo: ALL=(ALL) NOPASSWD:ALL
            home: /home/jenkins
            shell: /bin/bash
            lock_passwd: True
            gecos: Ubuntu
            groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev, docker]
            ssh-authorized-keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCSI+zOREGqL9V9fIy1o5fCFsGQfdJWtBFDoX9F/rF1kpXJZBJwcfBqVJqPGGIGGvafSgizIIQGD6qwFYLlIedI7iBApDxHj4ct1cnCo7cb0fHDe8+mwqnW2EmY5CJfwe341tUuUI/2mln6HDjCdCxU5htqilxD9J0GHF89ZFHhaCLex+A3BWZ8aPAJJr1+vyiorqnnb3oDf97tzQY+oBxOFkQPc3LThp+M6hlzjWyOQ1A6gv31bmYYw6xUwH8vb4o+5zdrAAAw5RV+aZ6F9iZbYbq9j0bK8uqsINbPbBAUcZug1TSzAVXEKsZMRaP/Qnbnz4mZsPP4uGN/PZ3tRgWL jenkins@3c44c24e0c91
        output: {all: '| tee -a /var/log/cloud-init-output.log'}
        final_message: "The system is finally up, after $UPTIME seconds"
    nics:
      - net-name: test_network
