---
- name: Create an externally accessible network named 'ext_network'.
  os_network:
    cloud: citycloud
    state: present
    provider_physical_network: ext-net
    name: test_network
    external: true