- name: Create a security group
  os_security_group:
    cloud: citycloud
    state: present
    name: test-security
    description: security group for test servers

- name:  Create a security group rule port 80
  os_security_group_rule:
    cloud: citycloud
    security_group: test-security
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

- name:  Create a security group rule port 443
  os_security_group_rule:
    cloud: citycloud
    security_group: test-security
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

- name:  Create a security group rule port 22
  os_security_group_rule:
    cloud: citycloud
    security_group: test-security
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name:  Create a security group rule port 8000
  os_security_group_rule:
    cloud: citycloud
    security_group: test-security
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

- name:  Create a security group rule port 3306
  os_security_group_rule:
    cloud: citycloud
    security_group: test-security
    protocol: tcp
    port_range_min: 3306
    port_range_max: 3306
    remote_ip_prefix: 0.0.0.0/0