---
- name: launch an instance
  os_server:
    state: present
    cloud: citycloud
    name: vm3
    image: 2feddaee-7c0d-4de1-a9c6-4a1c6be49cad
    key_name: ssh-key-fra2
    timeout: 200
    flavor: 2C-2GB-20GB
    security_groups: test-security,default
    userdata: |
      #cloud_config:
        package_update: true
        package_upgrade: true
        package_reboot_if_required: true
        hostname: 'gitServer'
        write_files:
          -content: |
              # My new /etc/hosts file
              127.0.0.1 localhost
              127.0.1.1 gitServer
              # The following lines are desirable for IPv6 capable hosts
              ::1 ip6-localhost ip6-loopback
              fe00::0 ip6-localnet
              ff00::0 ip6-mcastprefix
              ff02::1 ip6-allnodes
              ff02::2 ip6-allrouters
              ff02::3 ip6-allhosts
          path: /etc/hosts
        packages: apt-transport-https,ca-certificates,curl,software-properties-common,linux-image-extra-virtual,certbot
        fs_setup:
            ## rkt
          - device: /dev/vdb
            partition: 'auto'
            label: rkt
            filesystem: ext4
        mounts:
            - [ "LABEL=rkt", /mnt/docker_data ]
        runcmd:
          - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          - apt-get update
          - apt-get install -y docker-ce
        users:
          - default
          - name: gitAdmin
            plain_text_passwd: 'Test1234'
            sudo: ALL=(ALL) NOPASSWD:ALL
            home: /home/gitAdmin
            shell: /bin/bash
            lock_passwd: True
            gecos: Ubuntu
            groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev, docker]
            ssh-authorized-keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj1RkWnqvkuNo8zbm9yRA/bwXdqL1+d4vAFjO3dMMhCB+15s3f0b2G8oLKs7WsJgeVJl5ya/i3h4AXZKs1C7cT8Nipb7MMMo1SbVkcBglbEVMsJRWSRxnWfDl525CE5PiJK04ATBgSByfyE3vRvN406Wvde6EzF2x+IPohu69GfQuOh7jBs7aUoXuII4oyZ3U38Tf5gLL2LrvMaFsK9ggHzjB07aBeiz/Ve36bytsTUwvNsotdCeijKlCkDbzXcq+Ygvz83Um5NRJLAwXV1qKbJ28iy1qGgs9IHNUU+QR9Nrh/z92tiv9mhbiE7J9ys6+c8H1eFYsWX29gb5+hMpU7z0tya5nDjUV7nJAOp9Dg7ZA3UawkUilP3rRumluxMUowM3nOMI34Ef8u9qMvhae5o19DhVvsGhlVO/CruvLYzPJjQyE3V+srqNV6nF/2lzbF6Z/xTDEwwVc59Cu/yXG4MGB0KZH3mVko1dSzg6Xy+FW6P9Ef9u7TheHwOYp8c848/J/uUiq9PQd3ph4YGcrmBmug499o7cPNOJfV//EeTjdDFEZ+l6Ght0faTwcl8nneWxK6GhOJtp5mIleHnyYNuVcjURwOQ34fr97EFfMu+qjNBjEJmFqPiO5KuGOZUTGpr9YQ8t2XHa12DrRc96lfUgjwJ3KKpgPLXdXM2keDYQ== pleclercq@pleclercq-Precision-7510
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBgF2WsXljgFN8g6xGbG/O3anKrSiIxbDOqzJIyJqji0lODiM1U/ZZ55Qyy3kpEl4IA8IX/L2dS0AUBKRTttAlr8opnlteteUUgh8hBdu2b+2xvQMkbRnk7po5Jp2nTwVIT5w+lledNBg6cED6tnVPocO/pps4TEYaUyDKw8eOlNAlic6p4KrD/adk+0/KdMdMEK/yS/8YpMnjii6+9IRyn0Vx1wFF9BZM7XZ4MYU5uucrB8MeYIEMaVV4KvpjBYpvmwqUhsnp6G1/UMT02lBmnzzB67k1naLFGB4dNlnC+WPjltkgdCGnWXCpGaIFw3gl9WbUeiMj1LzwMEGjbcnT leletir@leletir-Cosmos2
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0UyVfQEGxRbBpfFFaT0Ubx9HmU1fmPHO2BfqFhXK75f/o2XNnCYVAk2yHY4P7IpA2YmSKl8/aUKDEhafNan0FyVkbBFEK9VdSRI5EnRZe04aDpc0Q5i8ARV5Sxt5AVb6rex8olTQZRll0D+M3485GGMogze7yb8Eo/vdGvIomNLMB0dp2smW2NReO9Jh7xyrKnK+S3eoSh3L9nuDYD1mmNXwiPmpPxGFxPw00RYnPUGiWP168KRqY4S5HMth7wap6tlj6AjNfe2eUqofZO/+cZpXgp1tD/7jSNJoHx14f5Pkf2fFVTq1/N9WBmhlk3BGTLheL0Dqs5+ivVHFoci7P gitAdmin@jenkinsServer
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS5fHCWb5/uyEAsxA5NWa3D3wpQhvvRc8hqVqtPd8zEUQzFfxRtzIRzHMknKY1XCeCnz5awwOoTXpAkv+RzvPjZQdtLNHKqPyr25GTEfrdoo+jGeORmmMFLtgTSf0OgIvx5K8VfOIGF97RUgdDEDp6g6RnjjJxvh0KwFcOZ40EdwtekY8Kebx1vHU6Ytm62jmaAKT6po7jg7YkOojGCbqwmwC8UfJFKcpCXHa9XvddaBj9R/70wUYmYTzn5o7y156ZL4WMhPc4DEpGM8MFzRtQpVEnzlnfjMxjIE1AvPO3kpQgLQUBPhtqqxwauxCvYGZyY5xMGq9A33Hy+ZYuzSRB jenkins@ad57f6b30ab8
        output: {all: '| tee -a /var/log/cloud-init-output.log'}
        final_message: "The system is finally up, after $UPTIME seconds"
    nics:
      - net-name: test_network
